### ISSUE TITLE
Incomplete merge of info.py

### ISSUE THREAD

**Issue by mwoodbri** [esoreq/minder-downloader#10]
`SyntaxError` when initialising package: see [info.py#L12-L23](https://github.com/esoreq/minder-downloader/blob/master/minder_downloader/info.py#L12-L23)

**Comment by esoreq** [comment]
Forgot to merge 🤦
Fixed now


From: Mark Woodbridge ***@***.***>
Date: Wednesday, 10 May 2023 at 11:00
To: esoreq/minder-downloader ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [esoreq/minder-downloader] Incomplete merge of info.py (Issue #10)
This email from ***@***.*** originates from outside Imperial. Do not click on links and attachments unless you recognise the sender. If you trust the sender, add them to your safe senders list<https://spam.ic.ac.uk/SpamConsole/Senders.aspx> to disable email stamping for this address.



SyntaxError when initialising package: see info.py#L12-L23

**Comment by mwoodbri** [comment]
Fixed by 0cc45f2
