### ISSUE TITLE
`requests` package is missing from dependencies list

### ISSUE THREAD

**Issue by mwoodbri** [esoreq/minder-downloader#2]
Steps to reproduce:

```sh
$ pip install minder-downloader
$ python -c 'import minder_downloader'
ModuleNotFoundError: No module named 'requests'
```

**Comment by esoreq** [comment]
Resolved

**Comment by mwoodbri** [comment]
Thank you!

**Comment by esoreq** [comment]
did you update to version 0.0.4?

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by mwoodbri** [comment]
`0.1.4`? Yep.

**Comment by esoreq** [comment]
ok will check later today

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
