### ISSUE TITLE
since/until required for undated datasets

### ISSUE THREAD

**Issue by mwoodbri** [esoreq/minder-downloader#3]
If you want to download e.g. `patients` dataset then you need to specify dummy values for dates, even though this dataset doesn't include dates. This is a little counter-intuitive (you can't pass `None` or omit the arguments):

```
md.load(datetime.now(), datetime.now(), ["patients"])
```

**Comment by esoreq** [comment]
Resolved by setting a default time period of a week unless specified explicitly
