### ISSUE TITLE
Enable data download in non-interactive environment

### ISSUE THREAD

**Issue by mwoodbri** [esoreq/minder-downloader#5]
Current interactive API token prompt is incompatible with running in a non-interactive environment e.g. Kubeflow.

Kubeflow provides tokens via files, so ideal situation would be to first check environment variable `RESEARCH_PORTAL_TOKEN_PATH`. If it is set then read token from that path. If not then prompt interactively, as currently.

The naming of this environment variable is consistent with that expected by [minder.research-portal-client](https://pypi.org/project/minder.research-portal-client/).

**Comment by esoreq** [comment]
Resolved - config now checks if RESEARCH_PORTAL_TOKEN_PATH exists

**Comment by mwoodbri** [comment]
Thanks - this very nearly works - but `RESEARCH_PORTAL_TOKEN_PATH` is a path, not a token. I will see if I can open an additional PR.

**Comment by esoreq** [comment]
is it a path that includes yaml file?

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by mwoodbri** [comment]
If set then it's a path to file containing token e.g:
```python
TOKEN = Path(os.environ['RESEARCH_PORTAL_TOKEN_PATH']).read_text()
```
